version: '3'
services:
  app:
    user: vscode
    build: 
      context: .
      dockerfile: Dockerfile  
    volumes:
      - .:/home/vscode/app:cached
      - ~/.ssh:/home/vscode/.ssh
      - ~/.gitconfig:/home/vscode/.gitconfig
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    command: /bin/sh -c "while sleep 1000; do :; done"  